### ISSUE TITLE
✨ Auth | Add user sign-up page

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/Scruminati.PublicUI#1]
### Description
As a user, I want to be able to sign up to Scruminati, so I can use its cool features

### Tasks
- [ ] Add sign-up button to menu
- [ ] Integrate with auth provider
- [ ] Test sign-up flow

### Acceptance Criteria
- [ ] Sign-up button on menu
- [ ] Sign-up button begins journey with auth provider
- [ ] On successful sign-up, user is redirected to the `/welcome` page
