### ISSUE TITLE
:sparkles: Auth | Add "delete account" functionality

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/Scruminati.PublicUI#2]
### Description
As a user, I want to be able to delete my account in Scruminati, because I don't like it.

### Tasks
- [ ] Add "Delete account" link in user's profile page
- [ ] Delete account button removes record from Scruminati database
- [ ] Delete account button removes record from auth provider

### Acceptance Criteria
- [ ] "Delete account" link at the bottom of the user profile page
- [ ] Delete account function removes record from Scruminati database
- [ ] Delete account function removes record from auth provider
